---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/lab/orders/{order_id}/specimens":
    post:
      summary: Add specimens to order
      tags:
      - Lab
      description: |
        Add specimens to an existing order.

        An order can be created without specifying specimens.
        This endpoint allows one to add specimens to that order.
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    concept_id:
                      type: integer
                    name:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                specimens:
                  type: array
                  items:
                    type: object
                    properties:
                      concept_id:
                        type: integer
                        description: Specimen type concept ID
                    required:
                    - concept_id
              required:
              - specimens
  "/api/v1/lab/orders":
    post:
      summary: Create order
      tags:
      - Lab
      description: |
        Create a lab order for a test.

        Broadly a lab order consists of a test type and a number of specimens.
        To each specimen is assigned a tracking number which can be used
        to query the status and results of the specimen.
      parameters: []
      security:
      - api_key: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    order_id:
                      type: integer
                    patient_id:
                      type: integer
                    encounter_id:
                      type: integer
                    order_date:
                      type: string
                      format: datetime
                    accession_number:
                      type: string
                    test_type:
                      type: object
                      properties:
                        concept_id:
                          type: integer
                        name:
                          type: string
                      required:
                      - concept_id
                      - name
                    requesting_clinician:
                      type: string
                      nullable: true
                    target_lab:
                      type: string
                    reason_for_test:
                      type: object
                      properties:
                        concept_id:
                          type: integer
                        name:
                          type: string
                      required:
                      - concept_id
                      - name
                    specimens:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          concept_id:
                            type: integer
                          name:
                            type: string
                          result:
                            type: string
                            nullable: true
                          result_date:
                            type: string
                            format: datetime
                            nullable: true
                        required:
                        - id
                        - concept_id
                        - name
                  required:
                  - order_id
                  - test_type
                  - reason_for_test
                  - accession_number
                  - patient_id
                  - order_date
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orders:
                  type: array
                  items:
                    properties:
                      encounter_id:
                        type: integer
                      test_type_id:
                        type: integer
                        description: Test type concept ID (see GET /lab/test_types)
                      specimens:
                        type: array
                        items:
                          type: object
                          properties:
                            concept_id:
                              type: integer
                              description: Specimen type concept ID (see GET /lab/test_types)
                      requesting_clinician:
                        type: string
                        description: Fullname of the clinician requesting the test
                          (defaults to orderer)
                      target_lab:
                        type: string
                      reason_for_test_id:
                        type: string
                        description: One of routine, targeted, or confirmatory
                    required:
                    - encounter_id
                    - test_type_id
                    - target_lab
                    - reason_for_test_id
    get:
      summary: Retrieve lab orders
      tags:
      - Lab
      description: Search/retrieve for lab orders.
      security:
      - api_key: []
      parameters:
      - name: patient_id
        in: query
        required: false
        description: Filter orders using patient_id
        schema:
          type: integer
      - name: accession_number
        in: query
        required: false
        description: Filter orders using sample accession number
        schema:
          type: integer
      - name: pending_results
        in: query
        required: false
        description: 'Select orders pending results [default: false]'
        schema:
          type: boolean
      - name: date
        in: query
        required: false
        description: Select results falling on a specific date
        schema:
          type: date
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    order_id:
                      type: integer
                    patient_id:
                      type: integer
                    encounter_id:
                      type: integer
                    order_date:
                      type: string
                      format: datetime
                    accession_number:
                      type: string
                    test_type:
                      type: object
                      properties:
                        concept_id:
                          type: integer
                        name:
                          type: string
                      required:
                      - concept_id
                      - name
                    requesting_clinician:
                      type: string
                      nullable: true
                    target_lab:
                      type: string
                    reason_for_test:
                      type: object
                      properties:
                        concept_id:
                          type: integer
                        name:
                          type: string
                      required:
                      - concept_id
                      - name
                    specimens:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          concept_id:
                            type: integer
                          name:
                            type: string
                          result:
                            type: string
                            nullable: true
                          result_date:
                            type: string
                            format: datetime
                            nullable: true
                        required:
                        - id
                        - concept_id
                        - name
                  required:
                  - order_id
                  - test_type
                  - reason_for_test
                  - accession_number
                  - patient_id
                  - order_date
  "/api/v1/lab/specimen_types":
    get:
      summary: Specimen types
      tags:
      - Lab
      description: Retrieve all specimen types
      security:
      - api_key: []
      parameters:
      - name: test_type
        in: query
        required: false
        description: Select specimen types having this test type only
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    concept_id:
                      type: integer
                    name:
                      type: string
                required:
                - concept_id
                - name
  "/api/v1/lab/test_types":
    get:
      summary: Test types
      tags:
      - Lab
      description: Retrieve all test types
      security:
      - api_key: []
      parameters:
      - name: specimen_type
        in: query
        required: false
        description: Select test types having this specimen type only
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    concept_id:
                      type: integer
                    name:
                      type: string
                required:
                - concept_id
                - name
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    bearer:
      type: bearer
      name: Authorization
      in: header
